services:
  postgres:
    container_name: helpdesk-postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
